###   Home Assistant plug-in configuration file   ###

name: "EspNow2mqtt"
description: "MQTT gateway for EspNow Flooding Mesh wireless devices"
version: "1.0.7"
url: "https://github.com/314159-r/esp_mesh_mqtt_gateway"
slug: "espnow2mqtt"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
services:
  - mqtt:need
uart: true

options:
  # serial port that esp gateway connected to
  serial_port: null
  serial_speed: 2
  # MQTT broker, URL, or HA Add-On "Hostmane" (found in Settings/Add-ons/[your-mqtt-broker]/info)
  mqtt_host: 'core-mosquitto'
  mqtt_port: 1883
  mqtt_username: null
  mqtt_password: null
  # mqtt topic prefix for messages from EspNow (sensors data)
  mqtt_from_mesh_prefix: 'espnow'
  # mqtt topic prefix for message to EspNow (commands)
  mqtt_to_mesh_prefix: 'espnow'
  # master/USB-gateway node name
  node_name: 'gw'
  # mesh ttl, Max no. of mesch node hops. (restransmitions)
  mesh_send_ttl: 5
  # publish timeout (milliseconds)
  pub_timeout: 50
  # publish transmit restry count
  pub_try_cnt: 5
schema:
  serial_port: str
  serial_speed: list(115200|230400|460800|921600|1843200)
  mqtt_host: str
  mqtt_port: int(1024,65536)
  mqtt_username: str
  mqtt_password: str
  mqtt_from_mesh_prefix: str
  mqtt_to_mesh_prefix: str
  node_name: str
  mesh_send_ttl: int(0,10)
  pub_timeout: int(10,1000)
  pub_try_cnt: int(1,30)
